name: update-repository
# <arch>-<vendor>-<os>-<env>

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
    # - cron: "0 2 * * *" # run at 2 AM UTC
  # push:
  #   tags:
  #     - "v*"

jobs:
  update-repository:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'noir-lang/aztec_backend'
          ref: 'kh-wasm-flake'
          path: 'aztec_backend'

      - name: Configure git
        run: |
          git config user.name kobyhallx
          git config user.email koby@aztecprotocol.com

      - name: Collect Revision
        id: collect-rev
        working-directory: 'aztec_backend'
        run: |
          echo "NOIR_REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "$(git rev-parse --short HEAD)" > .rev

      - name: Add .rev file to Git Tree
        run: |
          git add .rev

      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1.0.9
        with:
          key: nix-${{ hashFiles('aztec_backend/flake.lock') }}
          nix_file: 'flake.nix'

      - name: Build environment and Compile
        working-directory: 'aztec_backend'
        run: |
          nix build 

      - name: Zip
        run: |
          7z a -ttar -so -an ./aztec_backend/result/* | 7z a -si ./aztec_backend/aztec_backend.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aztec_backend.tar.gz
          path: ./aztec_backend/aztec_backend.tar.gz

      - name: Commit updates
        run: |
          git add nodejs web package.json
          git commit -m "updateing package"
          # noir@${{ steps.collect-rev.outputs.NOIR_REV_SHORT }}
          git push --force
